sudo: false
dist: trusty

rvm:
  - 2.2.9
  - 2.3.8
  - 2.4.5
  - 2.5.3

# Don't install local development gems on Travis, use parallel gem downloads
bundler_args: --without development --jobs 7

# Only test master
branches:
  only:
    - master

script: bundle exec rake
